
  type: pid_controller # this has to be exactly the same name as the controller py file
  args:
    lat:
      k_p: 0.75
      k_d: 0.02
      k_i: 0.4
    lon:
      k_p: 0.37
      k_d: 0.024
      k_i: 0.032
    dynamic: false # whether use dynamic pid setting
    dt: 0.05 # ${world.fixed_delta_seconds} # this should be equal to your simulation time-step
    max_brake: 1.0
    max_throttle: 1.0
    max_steering: 0.3
    